C:\repos\ai\1.txt
C:\repos\ai\11111.txt
C:\repos\ai\ai-onprem
C:\repos\ai\ai-onprem-multy
C:\repos\ai\appver
C:\repos\ai\backup
C:\repos\ai\ceph-chaos
C:\repos\ai\chaos-ceph
C:\repos\ai\checktls
C:\repos\ai\compare.md
C:\repos\ai\cosign
C:\repos\ai\dast
C:\repos\ai\dataprepper
C:\repos\ai\dkp
C:\repos\ai\grafana
C:\repos\ai\grafana-nginx
C:\repos\ai\grafana-service
C:\repos\ai\hostalias
C:\repos\ai\json
C:\repos\ai\k8s
C:\repos\ai\k8s-ha
C:\repos\ai\k8s-pros-cons-v2.md
C:\repos\ai\k8s-req
C:\repos\ai\keep-ha
C:\repos\ai\kk
C:\repos\ai\linux
C:\repos\ai\logs
C:\repos\ai\ls
C:\repos\ai\monitor-app
C:\repos\ai\net-checker
C:\repos\ai\openvpn
C:\repos\ai\otel
C:\repos\ai\prompt
C:\repos\ai\prompt2
C:\repos\ai\rados-expt
C:\repos\ai\redis
C:\repos\ai\runners
C:\repos\ai\s3-exporter
C:\repos\ai\suffix
C:\repos\ai\timep
C:\repos\ai\tree
C:\repos\ai\version
C:\repos\ai\zabbix
C:\repos\ai\zabbix2
C:\repos\ai\zabbix4
C:\repos\ai\zabbix5
C:\repos\ai\ai-onprem\claude
C:\repos\ai\ai-onprem\deep
C:\repos\ai\ai-onprem\perplexity.ai
C:\repos\ai\ai-onprem\promt.txt
C:\repos\ai\ai-onprem\promt2.txt
C:\repos\ai\ai-onprem\qwen
C:\repos\ai\ai-onprem\xx.txt
C:\repos\ai\ai-onprem\claude\1.txt
C:\repos\ai\ai-onprem\claude\2-1-llm_infrastructure_solution.md
C:\repos\ai\ai-onprem\claude\2-1.txt
C:\repos\ai\ai-onprem\claude\2-2-.txt
C:\repos\ai\ai-onprem\claude\2-2-prompt.txt
C:\repos\ai\ai-onprem\claude\llm_infrastructure_solution.md
C:\repos\ai\ai-onprem\claude\vector_search_system.md
C:\repos\ai\ai-onprem\deep\1.txt
C:\repos\ai\ai-onprem\perplexity.ai\2-1.txt
C:\repos\ai\ai-onprem\perplexity.ai\2-2.txt
C:\repos\ai\ai-onprem\perplexity.ai\2-3.txt
C:\repos\ai\ai-onprem\perplexity.ai\2-4.txt
C:\repos\ai\ai-onprem\perplexity.ai\2-5.txt
C:\repos\ai\ai-onprem\qwen\2.txt
C:\repos\ai\ai-onprem-multy\qwen-1.md
C:\repos\ai\ai-onprem-multy\qwen-2.md
C:\repos\ai\appver\c45-3.md
C:\repos\ai\appver\cc-3.md
C:\repos\ai\appver\claude-1.md
C:\repos\ai\appver\claude-2.md
C:\repos\ai\appver\g.json
C:\repos\ai\appver\g4-3-1.md
C:\repos\ai\appver\g5-3-1.md
C:\repos\ai\appver\g5-3.md
C:\repos\ai\appver\g5.md
C:\repos\ai\appver\gem-0.md
C:\repos\ai\appver\gem-1.md
C:\repos\ai\appver\gem-2.md
C:\repos\ai\appver\gem-3.md
C:\repos\ai\appver\promt.txt
C:\repos\ai\appver\promt2.txt
C:\repos\ai\appver\promt3.txt
C:\repos\ai\backup\3
C:\repos\ai\backup\gemini
C:\repos\ai\backup\promt3
C:\repos\ai\backup\promt4
C:\repos\ai\backup\3\chat
C:\repos\ai\backup\3\claude
C:\repos\ai\backup\3\deep
C:\repos\ai\backup\3\grok
C:\repos\ai\backup\3\perp
C:\repos\ai\backup\3\qwen
C:\repos\ai\backup\3\chat\ans.txt
C:\repos\ai\backup\3\claude\ans.txt
C:\repos\ai\backup\3\claude\installation_guide.md
C:\repos\ai\backup\3\claude\monitoring_script.sh
C:\repos\ai\backup\3\claude\s3_archive_script.sh
C:\repos\ai\backup\3\claude\s3_backup_script.sh
C:\repos\ai\backup\3\deep\ans.txt
C:\repos\ai\backup\3\grok\ans.txt
C:\repos\ai\backup\3\grok\backup_script.txt
C:\repos\ai\backup\3\perp\ans.txt
C:\repos\ai\backup\3\qwen\ans.txt
C:\repos\ai\backup\gemini\2.5.pto
C:\repos\ai\ceph-chaos\chat
C:\repos\ai\ceph-chaos\clude
C:\repos\ai\ceph-chaos\prompt.txt
C:\repos\ai\ceph-chaos\qwen
C:\repos\ai\ceph-chaos\clude\1.txt
C:\repos\ai\ceph-chaos\qwen\1.txt
C:\repos\ai\chaos-ceph\gem-pro-3-2.md
C:\repos\ai\chaos-ceph\gem-pro-3.md
C:\repos\ai\chaos-ceph\gem-pro-4.md
C:\repos\ai\chaos-ceph\gpt5-3.md
C:\repos\ai\chaos-ceph\gpt5-4-1.md
C:\repos\ai\chaos-ceph\gpt5-4.md
C:\repos\ai\chaos-ceph\grok4-4.md
C:\repos\ai\chaos-ceph\oss-120.md
C:\repos\ai\chaos-ceph\oss-20.md
C:\repos\ai\chaos-ceph\p1.txt
C:\repos\ai\chaos-ceph\p2.txt
C:\repos\ai\chaos-ceph\p3.txt
C:\repos\ai\chaos-ceph\p4.txt
C:\repos\ai\chaos-ceph\perplexity-4.md
C:\repos\ai\chaos-ceph\qwen-coder-2.md
C:\repos\ai\chaos-ceph\qwen-coder-3.md
C:\repos\ai\checktls\claude.md
C:\repos\ai\checktls\gem.md
C:\repos\ai\checktls\gpt5.md
C:\repos\ai\checktls\grok.md
C:\repos\ai\checktls\p1.txt
C:\repos\ai\cosign\claude-2.md
C:\repos\ai\cosign\claude.md
C:\repos\ai\cosign\gpt5-1.md
C:\repos\ai\cosign\gpt5-2.md
C:\repos\ai\cosign\gpt5-3.md
C:\repos\ai\cosign\grok-1.md
C:\repos\ai\cosign\grok-2.md
C:\repos\ai\cosign\grok-3.md
C:\repos\ai\cosign\p1.txt
C:\repos\ai\cosign\p2.txt
C:\repos\ai\cosign\p3.txt
C:\repos\ai\dast\claude-3-7-sonnet-20250219.txt
C:\repos\ai\dast\gemini pro 1.5.txt
C:\repos\ai\dast\gemini pro 2.5.txt
C:\repos\ai\dast\gpt-4.1-2025-04-14.txt
C:\repos\ai\dataprepper\claud4_5-3.md
C:\repos\ai\dataprepper\claude-ameria-3.md
C:\repos\ai\dataprepper\claude.json
C:\repos\ai\dataprepper\claude2.json
C:\repos\ai\dataprepper\clausde4_5-2.txt
C:\repos\ai\dataprepper\data_prepper_dashboard.json
C:\repos\ai\dataprepper\g.txt
C:\repos\ai\dataprepper\gem-3.md
C:\repos\ai\dataprepper\gem-ameria-3.md
C:\repos\ai\dataprepper\gemini-3.md
C:\repos\ai\dataprepper\gpt5-2.md
C:\repos\ai\dataprepper\gpt5-search-2.md
C:\repos\ai\dataprepper\gpt5.json
C:\repos\ai\dataprepper\grok-3.md
C:\repos\ai\dataprepper\grok4-search-2.md
C:\repos\ai\dataprepper\javaagent
C:\repos\ai\dataprepper\p2.txt
C:\repos\ai\dataprepper\p3-ameria.txt
C:\repos\ai\dataprepper\p3.txt
C:\repos\ai\dataprepper\qq
C:\repos\ai\dataprepper\qwen-3.md
C:\repos\ai\dataprepper\reten
C:\repos\ai\dataprepper\tune
C:\repos\ai\dataprepper\javaagent\gpt5.md
C:\repos\ai\dataprepper\javaagent\grok4.md
C:\repos\ai\dataprepper\reten\claude-0.md
C:\repos\ai\dataprepper\reten\claude-1.md
C:\repos\ai\dataprepper\reten\gem-1.md
C:\repos\ai\dataprepper\reten\gpt5-1.md
C:\repos\ai\dataprepper\reten\grok-1.md
C:\repos\ai\dataprepper\reten\promt-2.txt
C:\repos\ai\dataprepper\reten\promt.txt
C:\repos\ai\dataprepper\tune\gpt5.md
C:\repos\ai\dataprepper\tune\grok4.md
C:\repos\ai\dkp\DKP_CSE_d8_mirror_1_67_0.md
C:\repos\ai\dkp\DKP_CSE_Fix_FalcoMetricName_1_67_0.md
C:\repos\ai\dkp\DKP_CSE_Installation_1_67_0.md
C:\repos\ai\dkp\DKP_CSE_Installation_1_67_1.md
C:\repos\ai\dkp\DKP_CSE_Installation_1_67_3.md
C:\repos\ai\dkp\DKP_CSE_Modules_1_67_0.md
C:\repos\ai\dkp\readme.md
C:\repos\ai\grafana\promt1.txt
C:\repos\ai\grafana-nginx\gem3.5-3.md
C:\repos\ai\grafana-nginx\gpt5high-3.md
C:\repos\ai\grafana-nginx\newprompt1.txt
C:\repos\ai\grafana-nginx\qwen-1.md
C:\repos\ai\grafana-nginx\qwen-2.md
C:\repos\ai\grafana-nginx\qwen-3.md
C:\repos\ai\grafana-nginx\qwen-4.md
C:\repos\ai\grafana-nginx\qwen-doc-3.md
C:\repos\ai\grafana-service\claude
C:\repos\ai\grafana-service\deep
C:\repos\ai\grafana-service\grok
C:\repos\ai\grafana-service\lmarena
C:\repos\ai\grafana-service\promt1.txt
C:\repos\ai\grafana-service\promt2.txt
C:\repos\ai\grafana-service\claude\ans 1.txt
C:\repos\ai\grafana-service\claude\ans2.txt
C:\repos\ai\grafana-service\claude\grafana_table_query-2.md
C:\repos\ai\grafana-service\claude\grafana_table_query.md
C:\repos\ai\grafana-service\deep\ans.txt
C:\repos\ai\grafana-service\grok\ans.txt
C:\repos\ai\grafana-service\lmarena\ans-l.txt
C:\repos\ai\grafana-service\lmarena\ans-r.txt
C:\repos\ai\hostalias\d1.txt
C:\repos\ai\json\ans-l.txt
C:\repos\ai\json\ans-r.txt
C:\repos\ai\json\promt.txt
C:\repos\ai\k8s\1111
C:\repos\ai\k8s\claude-3.7 - 5.txt
C:\repos\ai\k8s\claude-sonnet-4-20250514 - 6.txt
C:\repos\ai\k8s\gemini pro 1.5 -6.txt
C:\repos\ai\k8s\gemini pro 2.5 -6.txt
C:\repos\ai\k8s\gemmini-pro 2.5 - 5.txt
C:\repos\ai\k8s\k8s-1.txt
C:\repos\ai\k8s\k8s-2-search-think.txt
C:\repos\ai\k8s\k8s-2.txt
C:\repos\ai\k8s\k8s-3-search-think.txt
C:\repos\ai\k8s\k8s-4-search-think.txt
C:\repos\ai\k8s\k8s-5-search-think.txt
C:\repos\ai\k8s\l-5.txt
C:\repos\ai\k8s\Llama 3.1 405B Instruct Turbo - 5.txt
C:\repos\ai\k8s\o4-mini-2025-04-16 - 5.txt
C:\repos\ai\k8s\p-k8s-1.txt
C:\repos\ai\k8s\p-k8s-2.txt
C:\repos\ai\k8s\p-k8s-3.txt
C:\repos\ai\k8s\p-k8s-4.txt
C:\repos\ai\k8s\p-k8s-5.txt
C:\repos\ai\k8s\p-k8s-6.txt
C:\repos\ai\k8s\p1.txt
C:\repos\ai\k8s\r-5.txt
C:\repos\ai\k8s-ha\1-1.plunt
C:\repos\ai\k8s-ha\1-2.plunt
C:\repos\ai\k8s-ha\1-4.plunt
C:\repos\ai\k8s-ha\1-5.plunt
C:\repos\ai\k8s-ha\1.plunt
C:\repos\ai\k8s-ha\2.plunt
C:\repos\ai\k8s-ha\3.plunt
C:\repos\ai\k8s-ha\p1.txt
C:\repos\ai\k8s-req\claude1.md
C:\repos\ai\k8s-req\claude2.md
C:\repos\ai\k8s-req\claude2d.md
C:\repos\ai\k8s-req\compare
C:\repos\ai\k8s-req\gpt5high.md
C:\repos\ai\k8s-req\gpt5high2.md
C:\repos\ai\k8s-req\gpt5high2d.md
C:\repos\ai\k8s-req\grok4.md
C:\repos\ai\k8s-req\promrt.txt
C:\repos\ai\k8s-req\qwen-d.md
C:\repos\ai\k8s-req\qwen-d2.md
C:\repos\ai\k8s-req\qwen1.md
C:\repos\ai\k8s-req\compare\claude-2.md
C:\repos\ai\k8s-req\compare\claude-search-2.md
C:\repos\ai\k8s-req\compare\gem-1.md
C:\repos\ai\k8s-req\compare\gem-2.md
C:\repos\ai\k8s-req\compare\gpt5-o11y.md
C:\repos\ai\k8s-req\compare\gpt5-search-2.md
C:\repos\ai\k8s-req\compare\gpt5.md
C:\repos\ai\k8s-req\compare\grok4-o11y.md
C:\repos\ai\k8s-req\compare\grok4-search-2.md
C:\repos\ai\k8s-req\compare\grok4.md
C:\repos\ai\k8s-req\compare\gtp5-p2.md
C:\repos\ai\k8s-req\compare\p1.txt
C:\repos\ai\k8s-req\compare\p2.txt
C:\repos\ai\k8s-req\compare\promt1.txt
C:\repos\ai\keep-ha\ckaude.md
C:\repos\ai\keep-ha\gem.md
C:\repos\ai\keep-ha\gpt5.md
C:\repos\ai\keep-ha\grok.md
C:\repos\ai\keep-ha\p1.txt
C:\repos\ai\keep-ha\you.md
C:\repos\ai\kk\1.md
C:\repos\ai\kk\gpt5-1.md
C:\repos\ai\kk\gpt5-2.md
C:\repos\ai\kk\v.md
C:\repos\ai\kk\v2.md
C:\repos\ai\kk\v3-1.md
C:\repos\ai\kk\v3.md
C:\repos\ai\linux\1.sh
C:\repos\ai\linux\2.sh
C:\repos\ai\logs\c-1.py
C:\repos\ai\logs\c-1.txt
C:\repos\ai\monitor-app\chat
C:\repos\ai\monitor-app\claude
C:\repos\ai\monitor-app\deep
C:\repos\ai\monitor-app\gemmini
C:\repos\ai\monitor-app\grok
C:\repos\ai\monitor-app\promt1.txt
C:\repos\ai\monitor-app\promt2.txt
C:\repos\ai\monitor-app\promt3.txt
C:\repos\ai\monitor-app\qwen
C:\repos\ai\monitor-app\xai
C:\repos\ai\monitor-app\chat\a-3.md
C:\repos\ai\monitor-app\claude\a-3.md
C:\repos\ai\monitor-app\deep\a-3.md
C:\repos\ai\monitor-app\gemmini\a-3-1.md
C:\repos\ai\monitor-app\gemmini\a-3-2.md
C:\repos\ai\monitor-app\grok\a-3.md
C:\repos\ai\monitor-app\qwen\a-3.md
C:\repos\ai\monitor-app\xai\a-3-1.md
C:\repos\ai\monitor-app\xai\a-3-2.md
C:\repos\ai\net-checker\aix4
C:\repos\ai\net-checker\claude
C:\repos\ai\net-checker\gemmini
C:\repos\ai\net-checker\grok
C:\repos\ai\net-checker\p1.txt
C:\repos\ai\net-checker\p2.txt
C:\repos\ai\net-checker\p3.txt
C:\repos\ai\net-checker\p4.txt
C:\repos\ai\net-checker\aix4\2.txt
C:\repos\ai\net-checker\claude\1
C:\repos\ai\net-checker\claude\1\net_checker_cleanup.txt
C:\repos\ai\net-checker\claude\1\net_checker_defaults.txt
C:\repos\ai\net-checker\claude\1\net_checker_example.txt
C:\repos\ai\net-checker\claude\1\net_checker_main.txt
C:\repos\ai\net-checker\claude\1\net_checker_meta.txt
C:\repos\ai\net-checker\claude\1\net_checker_mode1.txt
C:\repos\ai\net-checker\claude\1\net_checker_mode2.txt
C:\repos\ai\net-checker\claude\1\net_checker_readme.md
C:\repos\ai\net-checker\claude\1\net_checker_template.sh
C:\repos\ai\net-checker\gemmini\2.txt
C:\repos\ai\net-checker\grok\1-1.txt
C:\repos\ai\net-checker\grok\1.txt
C:\repos\ai\openvpn\claude.md
C:\repos\ai\openvpn\gem.md
C:\repos\ai\openvpn\gpt5.md
C:\repos\ai\openvpn\grok.md
C:\repos\ai\openvpn\p1.txt
C:\repos\ai\otel\1
C:\repos\ai\otel\1.py
C:\repos\ai\otel\11.txt
C:\repos\ai\otel\2
C:\repos\ai\otel\2.txt
C:\repos\ai\otel\3.txt
C:\repos\ai\otel\66
C:\repos\ai\otel\c.txt
C:\repos\ai\otel\g.txt
C:\repos\ai\otel\ot.md
C:\repos\ai\otel\poll.txt
C:\repos\ai\otel\Version.txt
C:\repos\ai\otel\1\opentelemetry-collector-dashboard.json
C:\repos\ai\otel\1\opentelemetry-collector-dashboard.md
C:\repos\ai\otel\2\cart-service-alerting.yml
C:\repos\ai\otel\2\opentelemetry-collector.json
C:\repos\ai\otel\2\spanmetrics-dashboard.json
C:\repos\ai\prompt\claude.md
C:\repos\ai\prompt\deep.md
C:\repos\ai\prompt\gem.md
C:\repos\ai\prompt\gpt5.md
C:\repos\ai\prompt\gpt5new.md
C:\repos\ai\prompt\grok.md
C:\repos\ai\prompt\ppl.md
C:\repos\ai\prompt2\claude-f.md
C:\repos\ai\prompt2\gem-f.md
C:\repos\ai\prompt2\gpt-f.md
C:\repos\ai\prompt2\gpt-p-full.md
C:\repos\ai\prompt2\gpt-p-short.md
C:\repos\ai\prompt2\gpt5-f.md
C:\repos\ai\prompt2\p1.md
C:\repos\ai\prompt2\qwen-f.md
C:\repos\ai\rados-expt\cg-1.py
C:\repos\ai\rados-expt\d-1.py
C:\repos\ai\rados-expt\d-2.py
C:\repos\ai\rados-expt\d-3.py
C:\repos\ai\rados-expt\d-4-1.py
C:\repos\ai\rados-expt\d-4-2.py
C:\repos\ai\rados-expt\d-4-3.py
C:\repos\ai\rados-expt\d-4.py
C:\repos\ai\rados-expt\d-6.py
C:\repos\ai\rados-expt\deepseek_plantuml_20250507_14ca38.txt
C:\repos\ai\rados-expt\deepseek_plantuml_20250507_3e6d38.txt
C:\repos\ai\rados-expt\deepseek_plantuml_20250507_6a0080.txt
C:\repos\ai\rados-expt\deepseek_plantuml_20250507_93eb41.txt
C:\repos\ai\rados-expt\deepseek_plantuml_20250507_a07650.txt
C:\repos\ai\rados-expt\deepseek_plantuml_20250507_b6a61d.txt
C:\repos\ai\rados-expt\deepseek_plantuml_20250507_c5ccd2.txt
C:\repos\ai\rados-expt\deepseek_plantuml_20250507_c6961c.txt
C:\repos\ai\rados-expt\gro
C:\repos\ai\rados-expt\r-src-cut.py
C:\repos\ai\rados-expt\r-src.py
C:\repos\ai\rados-expt\sber-1.py
C:\repos\ai\rados-expt\gro\dfd.plum
C:\repos\ai\rados-expt\gro\g-1.txt
C:\repos\ai\rados-expt\gro\g-2.txt
C:\repos\ai\rados-expt\gro\g-3.txt
C:\repos\ai\rados-expt\gro\g-4.txt
C:\repos\ai\rados-expt\gro\g-5.py
C:\repos\ai\rados-expt\gro\g-5.txt
C:\repos\ai\rados-expt\gro\sequence.plum
C:\repos\ai\rados-expt\gro\syntax-analiz.txt
C:\repos\ai\rados-expt\gro\unit-test.txt
C:\repos\ai\rados-expt\gro\диаграмма активности.plum
C:\repos\ai\rados-expt\gro\диаграмма классов.plum
C:\repos\ai\redis\claude-1.md
C:\repos\ai\redis\claude-2.md
C:\repos\ai\redis\gem-2.md
C:\repos\ai\redis\gem1.md
C:\repos\ai\redis\gpt5-1.md
C:\repos\ai\redis\gpt5-2.md
C:\repos\ai\redis\grok-1.md
C:\repos\ai\redis\grok-2.md
C:\repos\ai\redis\p1.txt
C:\repos\ai\redis\p2.txt
C:\repos\ai\runners\claude
C:\repos\ai\runners\deep
C:\repos\ai\runners\grok
C:\repos\ai\runners\perplexity.ai
C:\repos\ai\runners\promt 1.txt
C:\repos\ai\runners\promt 2.txt
C:\repos\ai\runners\qwen
C:\repos\ai\runners\claude\1
C:\repos\ai\runners\claude\2
C:\repos\ai\runners\claude\1\additional-configs.txt
C:\repos\ai\runners\claude\1\deployment-script.sh
C:\repos\ai\runners\claude\1\dockerfile-examples.txt
C:\repos\ai\runners\claude\1\gitlab-ci-kaniko-examples.txt
C:\repos\ai\runners\claude\1\gitlab-kaniko-architecture.md
C:\repos\ai\runners\claude\1\gitlab-runner-manifests.txt
C:\repos\ai\runners\claude\1\Архитектура GitLab Runners с Kaniko в Kubernetes.pdf
C:\repos\ai\runners\claude\2\deployment-scripts.sh
C:\repos\ai\runners\claude\2\gitlab-kaniko-architecture.md
C:\repos\ai\runners\claude\2\gitlab-runner-configs.txt
C:\repos\ai\runners\claude\2\monitoring-config.txt
C:\repos\ai\runners\claude\2\pipeline-examples.txt
C:\repos\ai\runners\deep\2
C:\repos\ai\runners\deep\2\ans 2.txt
C:\repos\ai\runners\deep\2\deepseek_mermaid_20250614_696806.png
C:\repos\ai\runners\grok\1
C:\repos\ai\runners\grok\2
C:\repos\ai\runners\grok\1\ans 1.txt
C:\repos\ai\runners\grok\1\GitLab Runner Kubernetes Deployment.yaml
C:\repos\ai\runners\grok\2\ans 2.txt
C:\repos\ai\runners\grok\2\Конфигурации и скрипты для развертывания GitLab Runner и Docker Registry.yaml
C:\repos\ai\runners\perplexity.ai\2
C:\repos\ai\runners\perplexity.ai\2\Архитектура решения GitLab Runners с Kaniko в Kube.md
C:\repos\ai\runners\perplexity.ai\2\Какие скрипты и манифесты необходимы для автоматич.md
C:\repos\ai\runners\qwen\1
C:\repos\ai\runners\qwen\2
C:\repos\ai\runners\qwen\1\ans 1-1.txt
C:\repos\ai\runners\qwen\1\ans 1-2.txt
C:\repos\ai\runners\qwen\1\ans 1.txt
C:\repos\ai\runners\qwen\2\ans 2.txt
C:\repos\ai\s3-exporter\s3-1.py
C:\repos\ai\s3-exporter\s3-2.py
C:\repos\ai\s3-exporter\s3.go
C:\repos\ai\suffix\claude.md
C:\repos\ai\suffix\gem.md
C:\repos\ai\suffix\gem2.md
C:\repos\ai\suffix\gem3.md
C:\repos\ai\suffix\gem4.md
C:\repos\ai\suffix\gem5.md
C:\repos\ai\suffix\gem6.md
C:\repos\ai\suffix\gpt5-6.md
C:\repos\ai\suffix\p1.txt
C:\repos\ai\timep\DOCS
C:\repos\ai\timep\LICENSE
C:\repos\ai\timep\README.md
C:\repos\ai\timep\TESTS
C:\repos\ai\timep\timep.bash
C:\repos\ai\timep\timep_flamegraph.pl
C:\repos\ai\timep\DOCS\reddit.md
C:\repos\ai\timep\TESTS\FORKRUN
C:\repos\ai\timep\TESTS\OUTPUT
C:\repos\ai\timep\TESTS\simple_example.bash
C:\repos\ai\timep\TESTS\timep.tests-exec.bash
C:\repos\ai\timep\TESTS\timep.tests.bash
C:\repos\ai\timep\TESTS\FORKRUN\flamegraph.full.svg
C:\repos\ai\timep\TESTS\FORKRUN\flamegraph.svg
C:\repos\ai\timep\TESTS\FORKRUN\out.flamegraph
C:\repos\ai\timep\TESTS\FORKRUN\out.flamegraph.full
C:\repos\ai\timep\TESTS\FORKRUN\out.profile
C:\repos\ai\timep\TESTS\FORKRUN\out.profile.full
C:\repos\ai\timep\TESTS\FORKRUN\readme.md
C:\repos\ai\timep\TESTS\OUTPUT\flamegraph.full.svg
C:\repos\ai\timep\TESTS\OUTPUT\flamegraph.svg
C:\repos\ai\timep\TESTS\OUTPUT\out.flamegraph
C:\repos\ai\timep\TESTS\OUTPUT\out.flamegraph.full
C:\repos\ai\timep\TESTS\OUTPUT\out.profile
C:\repos\ai\timep\TESTS\OUTPUT\out.profile.full
C:\repos\ai\version\11111.txt
C:\repos\ai\version\ans-1.txt
C:\repos\ai\version\ans-2.txt
C:\repos\ai\version\claude-analis-3.md
C:\repos\ai\version\claude-code-3.md
C:\repos\ai\version\claude-doc-3.md
C:\repos\ai\version\deep-d-3.md
C:\repos\ai\version\gem-cone-3.md
C:\repos\ai\version\gem-d-3-1.md
C:\repos\ai\version\gem-d-3-2.md
C:\repos\ai\version\gem-d-3.md
C:\repos\ai\version\gem-doc-3.md
C:\repos\ai\version\gpt5-code-3.md
C:\repos\ai\version\gpt5-d-3.md
C:\repos\ai\version\gpt5-doc-3.md
C:\repos\ai\version\grok-code-3.md
C:\repos\ai\version\grok-d-3.md
C:\repos\ai\version\grok-doc-3.md
C:\repos\ai\version\metr.txt
C:\repos\ai\version\metr2.txt
C:\repos\ai\version\promt1.txt
C:\repos\ai\version\promt2.txt
C:\repos\ai\version\promt3-a.txt
C:\repos\ai\version\promt3-c.txt
C:\repos\ai\version\promt3.txt
C:\repos\ai\version\qwen-code-3.md
C:\repos\ai\version\qwen-d-3.md
C:\repos\ai\zabbix\ceph-2-a.txt
C:\repos\ai\zabbix\ceph-2.txt
C:\repos\ai\zabbix\ceph-3.txt
C:\repos\ai\zabbix\ceph-4.txt
C:\repos\ai\zabbix\ceph-5-template.txt
C:\repos\ai\zabbix\ceph-5.txt
C:\repos\ai\zabbix\ceph-6.txt
C:\repos\ai\zabbix\ceph-7-1.txt
C:\repos\ai\zabbix\ceph-7-2.txt
C:\repos\ai\zabbix\ceph-7-3.txt
C:\repos\ai\zabbix\ceph-7.txt
C:\repos\ai\zabbix\ceph.txt
C:\repos\ai\zabbix\check_systemd_service.txt
C:\repos\ai\zabbix\claude
C:\repos\ai\zabbix\urls.txt
C:\repos\ai\zabbix\Zabbix Template for Ceph Monitoring.xml
C:\repos\ai\zabbix\Мониторинг Ceph с Zabbix Agent 1-4.markdown
C:\repos\ai\zabbix\Мониторинг Ceph с Zabbix Agent 1.markdown
C:\repos\ai\zabbix\claude\c-1-templ.txl
C:\repos\ai\zabbix\claude\c-1.txt
C:\repos\ai\zabbix\claude\c-2.txt
C:\repos\ai\zabbix2\6.4
C:\repos\ai\zabbix2\c1.txt
C:\repos\ai\zabbix2\check_radosgw_scripts.sh
C:\repos\ai\zabbix2\check_radosgw_vip_script.sh
C:\repos\ai\zabbix2\grok
C:\repos\ai\zabbix2\osd
C:\repos\ai\zabbix2\vip_discovery_script.sh
C:\repos\ai\zabbix2\zabbix_agent_config.txt
C:\repos\ai\zabbix2\zabbix_template.txt
C:\repos\ai\zabbix2\6.4\vip_discovery_script.sh
C:\repos\ai\zabbix2\6.4\zabbix_agent_config.txt
C:\repos\ai\zabbix2\6.4\zabbix_template_v6_4.txt
C:\repos\ai\zabbix2\osd\1.txt
C:\repos\ai\zabbix2\osd\2.txt
C:\repos\ai\zabbix4\1.txt
C:\repos\ai\zabbix4\ceph-osd-template.md
C:\repos\ai\zabbix5\1.txt
