# Local export path.
MINIO_VOLUMES=/srv/minio/data/

# default config
# CONFIG_DIR=/etc/minio

# default /var/lib/minio
# DATA_DIR=/var/lib/minio

# Use if you want to run Minio on a custom port.
# MINIO_OPTS="--address :9199"

# Server user.
MINIO_ROOT_USER=admin

# Server password.
MINIO_ROOT_PASSWORD=12121212


MINIO_OPTS="--address :9000 --console-address :9001"

#MINIO_ROOT_USER="minioadmin"
#MINIO_ROOT_PASSWORD="CHANGE_ME"

# Server logs -> local Vector
MINIO_LOGGER_WEBHOOK_ENABLE_local="on"
MINIO_LOGGER_WEBHOOK_ENDPOINT_local="http://127.0.0.1:8686/minio/server"
MINIO_LOGGER_WEBHOOK_BATCH_SIZE_local="1"
MINIO_LOGGER_WEBHOOK_QUEUE_SIZE_local="100000"
MINIO_LOGGER_WEBHOOK_QUEUE_DIR_local="/var/lib/minio/logger-webhook"
MINIO_LOGGER_WEBHOOK_MAX_RETRY_local="0"
MINIO_LOGGER_WEBHOOK_RETRY_INTERVAL_local="1s"
MINIO_LOGGER_WEBHOOK_HTTP_TIMEOUT_local="5s"

# Audit logs -> local Vector
MINIO_AUDIT_WEBHOOK_ENABLE_local="on"
MINIO_AUDIT_WEBHOOK_ENDPOINT_local="http://127.0.0.1:8686/minio/audit"
MINIO_AUDIT_WEBHOOK_QUEUE_SIZE_local="100000"
MINIO_AUDIT_WEBHOOK_QUEUE_DIR_local="/var/lib/minio/audit-webhook"
MINIO_AUDIT_WEBHOOK_MAX_RETRY_local="0"
MINIO_AUDIT_WEBHOOK_RETRY_INTERVAL_local="1s"
MINIO_AUDIT_WEBHOOK_HTTP_TIMEOUT_local="5s"