source "https://rubygems.org"

ruby "~> 3.3"

gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "rails", "~> 7.2.0"
gem "sidekiq", "~> 7.3.10"
gem "webrick", "~> 1.9"
gem "yabeda-activerecord", "0.1.2"
gem "yabeda-prometheus", "0.9.1"
gem "yabeda-puma-plugin", "0.9.0"
gem "yabeda-rails", "0.11.0"
gem "yabeda-sidekiq", "0.12.0"
