{
 "title": "Yabeda External HTTP requests",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPM (by host)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (rate(http_request_total[1m]) )",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "RPM (by status)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(http_response_total[1m]) )",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Duration (by host)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_response_duration_milliseconds_bucket[1m])) by (le, host))",
     "legendFormat": "{{ host }}"
    }
   ]
  }
 ]
}