{
 "title": "Yabeda::Puma::Plugin",
 "description": "Sample dashboard for puma web-server monitoring tool",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Waiting (queued) requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(puma_backlog)", "legendFormat": "Waiting requests" }
   ]
  },
  {
   "title": "Thread pool capacity",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(puma_running - puma_pool_capacity)",
     "legendFormat": "Busy threads"
    },
    { "expr": "sum(puma_running)", "legendFormat": "Running threads" },
    { "expr": "sum(puma_max_threads)", "legendFormat": "Maximum threads" }
   ]
  },
  {
   "title": "Worker processes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sum(puma_workers)", "legendFormat": "Total worker processes" },
    {
     "expr": "sum(puma_workers - puma_booted_workers)",
     "legendFormat": "Booting (not ready) processes"
    },
    { "expr": "sum(puma_old_workers)", "legendFormat": "Old worker processes" }
   ]
  }
 ]
}