{
 "title": "Fooder Rails Metrics All",
 "description": "Basic metrics for web applications built with Ruby on Rails  (Yabeda ).",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(rails_requests_total, instance)"
   },
   {
    "name": "controller",
    "query": "label_values(rails_requests_total, controller)"
   },
   {
    "name": "action",
    "query": "label_values(rails_requests_total, action)"
   },
   {
    "name": "method",
    "query": "label_values(rails_requests_total, method)"
   },
   {
    "name": "status",
    "query": "label_values(rails_requests_total, status)"
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rails_requests_total{instance=~\"$instance\",controller=~\"$controller\",action=~\"$action\",method=~\"$method\",status=~\"$status\"}[2m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Rails average response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rails_request_duration_seconds_sum{instance=~\"$instance\",controller=~\"$controller\",action=~\"$action\",method=~\"$method\",status=~\"$status\"}[2m]))\n/\nsum(rate(rails_request_duration_seconds_count{instance=~\"$instance\",controller=~\"$controller\",action=~\"$action\",method=~\"$method\",status=~\"$status\"}[2m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(rails_db_runtime_seconds_sum{instance=~\"$instance\",controller=~\"$controller\",action=~\"$action\",method=~\"$method\",status=~\"$status\"}[2m]))\n/\nsum(rate(rails_db_runtime_seconds_count{instance=~\"$instance\",controller=~\"$controller\",action=~\"$action\",method=~\"$method\",status=~\"$status\"}[2m]))",
     "legendFormat": "ActiveRecord"
    },
    {
     "expr": "sum(rate(rails_view_runtime_seconds_sum{instance=~\"$instance\",controller=~\"$controller\",action=~\"$action\",method=~\"$method\",status=~\"$status\"}[2m]))\n/\nsum(rate(rails_view_runtime_seconds_count{instance=~\"$instance\",controller=~\"$controller\",action=~\"$action\",method=~\"$method\",status=~\"$status\"}[2m]))",
     "legendFormat": "Views"
    }
   ]
  },
  {
   "title": "Rails 95% response time by endpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(rails_request_duration_seconds_bucket{instance=~\"$instance\",controller=~\"$controller\",action=~\"$action\",method=~\"$method\",status=~\"$status\"}[2m])) by (le,controller,action))",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "Rails max response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "max(sum(rate(rails_request_duration_seconds_sum{instance=~\"$instance\",controller=~\"$controller\",action=~\"$action\",method=~\"$method\",status=~\"$status\"}[2m]))\n/\nsum(rate(rails_request_duration_seconds_count{instance=~\"$instance\",controller=~\"$controller\",action=~\"$action\",method=~\"$method\",status=~\"$status\"}[2m])))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(rails_db_runtime_seconds_sum{instance=~\"$instance\",controller=~\"$controller\",action=~\"$action\",method=~\"$method\",status=~\"$status\"}[2m]))\n/\nsum(rate(rails_db_runtime_seconds_count{instance=~\"$instance\",controller=~\"$controller\",action=~\"$action\",method=~\"$method\",status=~\"$status\"}[2m]))",
     "legendFormat": "ActiveRecord"
    },
    {
     "expr": "sum(rate(rails_view_runtime_seconds_sum{instance=~\"$instance\",controller=~\"$controller\",action=~\"$action\",method=~\"$method\",status=~\"$status\"}[2m]))\n/\nsum(rate(rails_view_runtime_seconds_count{instance=~\"$instance\",controller=~\"$controller\",action=~\"$action\",method=~\"$method\",status=~\"$status\"}[2m]))",
     "legendFormat": "Views"
    }
   ]
  },
  {
   "title": "Throughput / Endpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rails_requests_total{instance=~\"$instance\",controller=~\"$controller\",action=~\"$action\",method=~\"$method\",status=~\"$status\"}[2m])) by (controller, action)",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "Errors / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rails_requests_total{instance=~\"$instance\",controller=~\"$controller\",action=~\"$action\",method=~\"$method\",status=~\"^[45].*\"}[2m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Slow Actions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,avg(rate(rails_request_duration_seconds_sum{instance=~\"$instance\"}[1w]) / rate(rails_request_duration_seconds_count{instance=~\"$instance\"}[1w])) by (controller, action))"
    }
   ]
  },
  {
   "title": "Most Frequent Actions / Day",
   "type": "table",
   "description": "Average number of requests per day during last week",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,sum(rate(rails_request_duration_seconds_count{instance=~\"$instance\",controller!=\"active_storage/disk\",controller!=\"active_storage/representations\"}[1w]) * 3600 * 24) by (controller, action))"
    }
   ]
  }
 ]
}