# Глава 11. Модули Deckhouse как часть модели угроз

- Главная идея
  - Модуль закрывает одни риски
  - Модуль создаёт новые риски
  - Нужно решение: включить, пилотировать, отложить
- Термины
  - Поверхность атаки
  - Граница доверия
  - Blast radius
  - Guardrails
  - Supply chain
- Шаблон оценки
  - Какой риск закрываем
  - Какая граница доверия меняется
  - Какие привилегии появляются
  - Какие данные видит модуль
  - Что будет при компрометации
  - Какие guardrails обязательны
  - Какой контрпример запрещает включение
- Istio multicluster
  - Закрывает
    - mTLS
    - Явные AuthorizationPolicy
    - Меньше ручных сетевых исключений
    - Наблюдаемость service-to-service traffic
  - Создаёт
    - Общий trust root
    - Lateral movement между кластерами
    - Сложность диагностики
    - Риск смешать dev/test/prod
  - Хорошее решение
    - Конкретный service account
    - Конкретный namespace
    - Конкретный метод и path
  - Контрпример
    - principals ["*"]
    - Federation для всех окружений
- control-plane-manager
  - Закрывает дрейф control plane
  - Управляет сертификатами
  - Создаёт риск высокопривилегированной автоматизации
  - Guardrails
    - Review
    - Staging
    - Backup etcd
    - Окно обслуживания
- deckhouse updates
  - Закрывает patch lag
  - Создаёт supply chain зависимость
  - Release channel
  - ModuleSource
  - Staging before prod
- ingress-nginx
  - Централизует внешний вход
  - TLS
  - Риск wildcard и публичных админок
  - Отдельные ingressClass
  - allow-list источников
- registry и registry-packages-proxy
  - Закрытый контур
  - Контроль источников
  - Риск компрометации внутреннего registry
  - Digest pinning
  - Scanning
  - Ограничение push-прав
- monitoring и Upmeter
  - Закрывает слепоту
  - Метрики и доступность
  - Риск утечки через dashboards и labels
  - RBAC
  - Владельцы alerts
- Лабораторная
  - Выбрать три модуля
  - Заполнить risk matrix
  - Написать хорошее решение
  - Написать контрпример
  - Принять решение
