---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-runners

---
# Сервисный аккаунт
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner
  namespace: gitlab-runners
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-runner-1
