apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    training.deckhouse.io/course: security-dkp
    training.deckhouse.io/app: shop-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: orders
  labels:
    training.deckhouse.io/course: security-dkp
    training.deckhouse.io/app: shop-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: payments
  labels:
    training.deckhouse.io/course: security-dkp
    training.deckhouse.io/app: shop-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-tools
  labels:
    training.deckhouse.io/course: security-dkp
    training.deckhouse.io/app: shop-demo
