apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-api
  namespace: payments
---
apiVersion: v1
kind: Secret
metadata:
  name: payments-static-secret
  namespace: payments
type: Opaque
stringData:
  API_TOKEN: training-only-static-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
  namespace: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
    spec:
      serviceAccountName: payments-api
      containers:
        - name: app
          image: hashicorp/http-echo:1.0.0
          args:
            - -text=payments ok
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: payments-static-secret
                  key: API_TOKEN
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: payments
spec:
  selector:
    app: payments-api
  ports:
    - port: 80
      targetPort: 5678
